[project]
name = "msc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["msc-base", "msc-droidcast", "msc-minicap", "msc-adb", "msc-mumu"]
