[project]
name = "msc-mumu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mmumu",
    "msc-base",
    "opencv-python>=4.11.0.86",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/msc"]

[tool.uv.sources]
msc-base = { workspace = true }
mmumu = { git = "https://github.com/NakanoSanku/mmumu" }
